def lectura_función():
    print("Una función es un conjunto de instrucciones que realizan alguna tarea y esta tarea va a invocar más de una vez un mismo programa.")
    print("a) Pueden recibir o no parámetros")
    print("b) Pueden retornar un valor o pueden no retornar ningun valor")
    print("""Para escribir una función se tiene que comenzar la función con la palabra "def" """)
    print("")
    print("Ejemplo:")
    print("def DoSomething():")
    print("    value = 1")
    print("    return value")
    print("")
    print("""En este caso se crea la función utilizando la palabra "def". \n Luego, se nombra la función.\n Se le manda una labor que hacer a la función, la cual recibe un valor de uno y, \n finalmente, se retorna el valor asignado. """)
    print("")
    print("Hay que principalmente tener cuidado con algunas cosas")
    print("")
    print("1) siempre define tu función")
    print("""2) Acuerdate que el nombre de tu función tiene que ser una sola palabra. Puede tener "_", "-", "/" o cualquier otro caracter para unir palabras pero no pueden haber espacios entre palabras """)
    print("3) siempre tienen que haber brackets al terminar de escribir la función")
    print("""4) La función siempre tiene que terminar con la palabra "return" """)
    print("5) Si se quiere llamar a la función, se tiene que escribir su nombre afuera")
    print("")
    print("Otro ejemplo:")
    print("")
    print("Cree una función la cual cambie grados centigrados a Kelvin")
    print("")
    print("def fahr_to_Kelvin(temp):")
    print("   return((temp-32)*(5/9))")
    print("""temperatura=int(input("Ingresa tu temperatura en farenheit":))""")
    print("""print("fahr_to_kelvin(temperatura)""")
    print("")
    print("")
    print("También se pueden utilizar funciones dentro de funciones")
    print("Un ejemplo es la función print")
    print("Si se escribe la función print dentro de una función se estaría imprimiendo el valor indicado")
    print("")
    print("Por ejemplo:")
    print("")
    print("")
    print("def licencia():")
    print("""    print("Copyright 2017")""")
    print("""    print("AUS204")""")
    print("      return")
    print("licencia()")
    print("")
    print("")
    print("Otro probelam que se puede encontrar con las funciones es la definición de las variables. Acá hay una función ara ilustrarlo:")
    print("")
    print("def escribe_suma():")
    print("    suma=a+b")
    print("""    print("La suma de {a} y {b} es: {suma}")""")
    print("    return")
    print("a=4")
    print("b=5")
    print("escribe_suma()")
    print("")
    print("")
    print("El problema de esta función es que los valores son muy específicos ya que la función solo funcionaría con los valores a y b. Además siempre va a imprimir el resultado, lo cual no siempre es útil")
    print("Esto puede solucionarse")
    print("")
    print("Aca está la función mejorada:")
    print("")
    print("")
    print("def escribe_suma(x,y):")
    print("    suma=x+y")
    print("    return suma")
    print("a=4")
    print("b=5")
    print("escribe_suma(a,b)")
    print("""print(f"La suma de {a} y {b} es: {suma}") """)
    print("")
    print("¿Vez la diferencia?")
    print("El último programa es más general y por lo tanto más reutilizable ya que generaliza algunos términos")
    print("")
    print("Un último ejemplo")
    print("")
    print("")
    print("lado = 0")
    print("def main():")
    print("    lado = int(input())")
    print("    print(cuadrado_área())")
    print("    return")
    print("")
    print("def cuadrado_área():")
    print("    return lado**2")
    print("")
    print("")
    print("Ya que la variable lado esta afuera de los scopes de las otras funciones, se puede utilizar en ambas funciones y puede ser accedida por cualquier parte")
    print("Sino, se tendría que variar la variable lado a otra variable para la función cuadrado_area")
    return
#lectura_función()
def ejercicio_funciones():
    print("Ahora, harás un pequeño quiz para ver si has comprendido el tema de funciones. Tienes que escribir el output de los siguientes códigos:")
    print("")
    print("Constrains: Ingresa solo el número")
    print("")
    print("Numero 1 ,Función 1:")
    print("")
    print("")
    print("def f(x):")
    print("    return g(x)+h(x)")
    print("")
    print("def g(x):")
    print("    return 4*h(x)")
    print("")
    print("def h(x):")
    print("    return x**2")
    print("")
    print("print(f(2))")
    print("")
    output1funciones = int(input("Ingresa el output de la función: "))
    print("")
    print("")
    print("Numero 2 ,Función 1:")
    print("")
    print("")
    print("def f(x):")
    print("    return g(x)+h(x)")
    print("")
    print("def g(x):")
    print("    return 4*h(x)")
    print("")
    print("def h(x):")
    print("    return x**2")
    print("")
    print("print(f(3))")
    print("")
    output2funciones = int(input("Ingresa el output de la función: "))
    print("")
    print("")
    print("Numero 3 ,Función 1:")
    print("")
    print("")
    print("def f(x):")
    print("    return g(x)+h(x)")
    print("")
    print("def g(x):")
    print("    return 4*h(x)")
    print("")
    print("def h(x):")
    print("    return x**2")
    print("")
    print("print(f(1))")
    print("")
    output3funciones = int(input("Ingresa el output de la función: "))
    print("")
    print("")
    print("")
    print("Numero 1 , Función 2")
    print("")
    print("")
    print("def funcion_misteriosa(n):")
    print("    suma = 0")
    print("    for i in range(n):")
    print("        suma=suma+i")
    print("    return(suma)")
    print("")
    print("print(funcion_misteriosa(4))")
    print("")
    output4funciones = int(input("Ingresa el output de la función: "))
    print("")
    print("")
    print("Numero 2 , Función 2")
    print("")
    print("")
    print("def funcion_misteriosa(n):")
    print("    suma = 0")
    print("    for i in range(n):")
    print("        suma=suma+i")
    print("    return(suma)")
    print("")
    print("print(funcion_misteriosa(8))")
    print("")
    output5funciones = int(input("Ingresa el output de la función: "))
    print("")
    print("")
    print("Numero 3 , Función 2")
    print("")
    print("")
    print("def funcion_misteriosa(n):")
    print("    suma = 0")
    print("    for i in range(n):")
    print("        suma=suma+i")
    print("    return(sum)a")
    print("")
    print("print(funcion_misteriosa(6))")
    print("")
    output6funciones = int(input("Ingresa el output de la función: "))
    print("")
    print("")
    print("")
    print("Numero 1, Función 3")
    print("")
    print("")
    print("")
    print("def funcion_x(variable):")
    print("    contador = 0")
    print("    for i in variable:")
    print("        if i in ['a', 'e','i','o','u']:")
    print("            contador=contador + 1")
    print("    return contador")
    print("")
    print("print(funcion_x(['amigo'])")
    print("")
    output7funciones = int(input("Ingresa el output de la función: "))
    print("")
    print("")
    print("")
    print("Numero 2, Función 3")
    print("")
    print("")
    print("")
    print("def funcion_x(variable):")
    print("    contador = 0")
    print("    for i in variable:")
    print("        if i in ['a', 'e','i','o','u']:")
    print("            contador=contador + 1")
    print("    return contador")
    print("")
    print("print(funcion_x(['hasta'])")
    print("")
    output8funciones = int(input("Ingresa el output de la función: "))
    print("")
    print("")
    print("")
    print("Numero 3, Función 3")
    print("")
    print("")
    print("")
    print("def funcion_x(variable):")
    print("    contador = 0")
    print("    for i in variable:")
    print("        if i in ['a', 'e','i','o','u']:")
    print("            contador=contador + 1")
    print("    return contador")
    print("")
    print("print(funcion_x(['Soy un hacker'])")
    print("")
    output9funciones = int(input("Ingresa el output de la función: "))
    contador_funciones = 0
    if output1funciones == 20:
        contador_funciones += 1
    if output2funciones == 45:
        contador_funciones += 1
    if output3funciones == 5:
        contador_funciones += 1
    if output4funciones == 6:
        contador_funciones += 1
    if output5funciones == 28:
        contador_funciones += 1
    if output6funciones == 15:
        contador_funciones += 1
    if output7funciones == 3:
        contador_funciones += 1
    if output8funciones == 2:
        contador_funciones += 1
    if output9funciones == 4:
        contador_funciones += 1
    if contador_funciones == 9:
        print("Muy bien, sacaste todo bien")
        volver_a_intentar = input("Si quieres volver a intentar los ejercicios escribe la palabra si acá: ")
    else:
        print("sacaste ",contador_funciones,"/sobre 9 preguntas bien")
        print("¿Quieres volver a intentar los ejercicios?")
        volver_a_intentar = input("Si quieres volver a intentar los ejercicios escribe la palabra si acá: ")
    while volver_a_intentar == "si":
            print(
                "Ahora, haras un pequeño quiz para ver si has comprendido el tema de funciones. Tienes que escribir el output de los siguientes códigos")
            print("Constrains: Ingresa solo el número")
            print("")
            print("Numero 1 ,Función 1:")
            print("")
            print("")
            print("def f(x):")
            print("    return g(x)+h(x)")
            print("")
            print("def g(x):")
            print("    return 4*h(x)")
            print("")
            print("def h(x):")
            print("    return x**2")
            print("")
            print("print(f(2))")
            print("")
            output1funciones = int(input("Ingresa el output de la función: "))
            print("")
            print("")
            print("Numero 2 ,Función 1:")
            print("")
            print("")
            print("def f(x):")
            print("    return g(x)+h(x)")
            print("")
            print("def g(x):")
            print("    return 4*h(x)")
            print("")
            print("def h(x):")
            print("    return x**2")
            print("")
            print("print(f(3))")
            print("")
            output2funciones = int(input("Ingresa el output de la función: "))
            print("")
            print("")
            print("Numero 3 ,Función 1:")
            print("")
            print("")
            print("def f(x):")
            print("    return g(x)+h(x)")
            print("")
            print("def g(x):")
            print("    return 4*h(x)")
            print("")
            print("def h(x):")
            print("    return x**2")
            print("")
            print("print(f(1))")
            print("")
            output3funciones = int(input("Ingresa el output de la función: "))
            print("")
            print("")
            print("")
            print("Numero 1 , Función 2")
            print("")
            print("")
            print("def funcion_misteriosa(n):")
            print("    suma = 0")
            print("    for i in range(n):")
            print("        suma=suma+i")
            print("    return(suma")
            print("")
            print("print(funcion_misteriosa(4)")
            print("")
            output4funciones = int(input("Ingresa el output de la función: "))
            print("")
            print("")
            print("Numero 2 , Función 2")
            print("")
            print("")
            print("def funcion_misteriosa(n):")
            print("    suma = 0")
            print("    for i in range(n):")
            print("        suma=suma+i")
            print("    return(suma")
            print("")
            print("print(funcion_misteriosa(8)")
            print("")
            output5funciones = int(input("Ingresa el output de la función: "))
            print("")
            print("")
            print("Numero 3 , Función 2")
            print("")
            print("")
            print("def funcion_misteriosa(n):")
            print("    suma = 0")
            print("    for i in range(n):")
            print("        suma=suma+i")
            print("    return(suma")
            print("")
            print("print(funcion_misteriosa(6)")
            print("")
            output6funciones = int(input("Ingresa el output de la función: "))
            print("")
            print("")
            print("")
            print("Numero 1, Función 3")
            print("")
            print("")
            print("")
            print("def funcion_x(variable):")
            print("    contador = 0")
            print("    for i in variable:")
            print("        if i in ['a', 'e','i','o','u']:")
            print("            contador=contador + 1")
            print("    return contador")
            print("")
            print("print(funcion_x(['amigo']")
            print("")
            output7funciones = int(input("Ingresa el output de la función: "))
            print("")
            print("")
            print("")
            print("Numero 2, Función 3")
            print("")
            print("")
            print("")
            print("def funcion_x(variable):")
            print("    contador = 0")
            print("    for i in variable:")
            print("        if i in ['a', 'e','i','o','u']:")
            print("            contador=contador + 1")
            print("    return contador")
            print("")
            print("print(funcion_x(['hasta']")
            print("")
            output8funciones = int(input("Ingresa el output de la función: "))
            print("")
            print("")
            print("")
            print("Numero 3, Función 3")
            print("")
            print("")
            print("")
            print("def funcion_x(variable):")
            print("    contador = 0")
            print("    for i in variable:")
            print("        if i in ['a', 'e','i','o','u']:")
            print("            contador=contador + 1")
            print("    return contador")
            print("")
            print("print(funcion_x(['Soy un hacker']")
            print("")
            output9funciones = int(input("Ingresa el output de la función: "))
            contador_funciones = 0
            if output1funciones == 20:
                contador_funciones += 1
            if output2funciones == 45:
                contador_funciones += 1
            if output3funciones == 5:
                contador_funciones += 1
            if output4funciones == 6:
                contador_funciones += 1
            if output5funciones == 28:
                contador_funciones += 1
            if output6funciones == 15:
                contador_funciones += 1
            if output7funciones == 3:
                contador_funciones += 1
            if output8funciones == 2:
                contador_funciones += 1
            if output9funciones == 4:
                contador_funciones += 1
            if contador_funciones == 9:
                print("Muy bien, sacaste todo bien")
                volver_a_intentar = input("Si quieres volver a intentar los ejercicios escribe la palabra si acá: ")
            else:
                print("sacaste ", contador_funciones, "/sobre 9 preguntas bien")
                print("¿Quieres volver a intentar los ejercicios?")
                volver_a_intentar = input("Si quieres volver a intentar los ejercicios escribe la palabra si acá: ")
    return()
ejercicio_funciones()
        







